### ISSUE TITLE
the file in ai2thor/dataset

### ISSUE THREAD

**Issue by bill4689** [Gary3410/TaPA#2]
How are the files in the ai2thor/dataset path generated? I have some questions about dividing the entire scene into several sub-regions by the K-means clustering method as you mentioned in your paper. Can you share the codes? thank you

**Comment by Gary3410** [comment]
Thank you for your interest in TaPA. K-means clustering code has been uploaded. Hope it can help you.
https://github.com/Gary3410/TaPA/blob/96d62ff156a04b417019a067add907e7730af5c1/create_dataset/create_partial_vision_dataset.py#L105-L119

**Comment by bill4689** [comment]
ok，thank you
