### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by Garsonjw** [Gary3410/TaPA#3]
Hi, I want to know if there is an image as input in the inference stage, and where is Detic used in the inference stage?

**Comment by Gary3410** [comment]
Hi! The overall inference stage of TaPA requires image inputs to provide the necessary information. You can find it in generate/adapter_detic_robot_eval_random.py.
Also, we have added new scripts that use Detic inference for ease of use.
https://github.com/Gary3410/TaPA/blob/13181269cc18f62616643041ec9e0134e14c9758/generate/adapter_with_detic.py#L197-L206
You can find the usages of the new scripts [here](https://github.com/Gary3410/TaPA#running-the-inference).
Hope this can help you!

**Comment by Garsonjw** [comment]
> Hi! The overall inference stage of TaPA requires image inputs to provide the necessary information. You can find it in generate/adapter_detic_robot_eval_random.py. Also, we have added new scripts that use Detic inference for ease of use.
> 
> https://github.com/Gary3410/TaPA/blob/13181269cc18f62616643041ec9e0134e14c9758/generate/adapter_with_detic.py#L197-L206
> 
> 
> You can find the usages of the new scripts [here](https://github.com/Gary3410/TaPA#running-the-inference).
> Hope this can help you!

Thanks for your reply! In the adapter_detic_robot_eval_random.py I saw the code for loading imgs. I would like to know how can I get the following imgs. I did not find this related dataset imgs in ai2thor/dataset.
![image](https://github.com/Gary3410/TaPA/assets/128013411/e3488abd-d61e-43a1-bf63-8085f6a71ad6)

**Comment by Gary3410** [comment]
Hi, you can run the following code to get the following imgs.
```bash
python create_partial_vision_dataset.py
python create_vision_dataset.py
```
The corresponding datasets can then be found in `ai2thor/dataset`.

**Comment by Garsonjw** [comment]
Thanks！
