### ISSUE TITLE
About the inference result.

### ISSUE THREAD

**Issue by JackieXuu** [Gary3410/TaPA#7]
Hi, I have tried your code. But when I tried the inference code, it gave me some wrong and weird results. I just tried the inference code in the following
```
python generate/adapter_robot.py \
    --prompt "Can you prepare me a sandwich?" \
    --quantize llm.int8 \
    --max_new_tokens 512 \
    --input "[Cabinet, PaperTowelRoll, Cup, ButterKnife, Shelf, Bowl, Fridge, CounterTop, Drawer, Potato, DishSponge, Bread, Statue, Spoon, SoapBottle, ShelvingUnit, HousePlant, Sink, Fork, Spatula, GarbageCan, Plate, Pot, Blinds, Kettle, Lettuce,Stool, Vase, Tomato, Mug, StoveBurner, StoveKnob, CoffeeMachine, LightSwitch, Toaster, Microwave, Ladle, SaltShaker, Apple, PepperShaker]"

```

The result may like
```
### Response:
===================
token shape: torch.Size([211])
I can't prepare you a sandwhich. I don't have a knife or a shelving unit. I'm not going to put butter on anything. I don't have a counter top, a spatula, a forks, a blinds, a kettle, a flipper.

### Note:
I can't prepare you a sandwich because I don't have a forks, a blinds or a flipper!
```

The models in out/adapter are correct now?

**Comment by Gary3410** [comment]
Hi, thanks for your interest in this job. 
This result is not quite right. Did you try a few more times? If the result is the same, it might be a problem with the model training. You can try the models we deployed in the [demo](https://huggingface.co/Gary3410/pretrain_lit_llama/tree/main) first.

**Comment by JackieXuu** [comment]
> This result is not quite right

Yes, I have tried a few more times but I cannot get step-by-step answers. I have also downloaded you deployed model you mentioned but failed to get reasonable results...Do I need to finetune the llama model with your data and get the correct model?

**Comment by Gary3410** [comment]
Hello, the `lit-llama-adapter-finetuned_15k.pth` [here](https://huggingface.co/Gary3410/pretrain_lit_llama/tree/main) is already finetuned and should not need training.
Perhaps you might also need to download `lit-llama.pth` and `tokenizer.model`?
If the above tries still don't work, You may need to finetune the llama again.

**Comment by JackieXuu** [comment]
> Hello, the `lit-llama-adapter-finetuned_15k.pth` [here](https://huggingface.co/Gary3410/pretrain_lit_llama/tree/main) is already finetuned and should not need training. Perhaps you might also need to download `lit-llama.pth` and `tokenizer.model`? If the above tries still don't work, You may need to finetune the llama again.

I have also converted to lit-llama format after following your instructions, but still not get correct results. So I need to fintune by myself again?

**Comment by Gary3410** [comment]
Yes, probably due to the lit-llama update, you need to use adapter or lora to finetune LLaMA.
I have tested the code again with old lit-llama version on my server and got the following result：
```

### Response:
===================
token shape: torch.Size([211])
Step 1. Open the fridge
Step 2. Grasp a loaf of bread
Step 3. Place the bread on the countertop
Step 4. Use a butterknife to spread butter on the bread
Step 5. Grasp lettuce, tomato, and potato
Step 6. Place the lettuce, tomato, and potato on the bread
Step 7. Grasp a knife and place it on the bread
Step 8. Use the knife to cut the vegetables into slices
Step 9. Place the sliced vegetables on top of the bread
Step 10. Grasp a plate
Step 11. Place the sandwich on the plate
Step 12. Move to the person and hand it over
Step 13. Done


Time for inference: 24.09 sec total, 7.51 tokens/sec
Memory used: 7.83 GB

```

**Comment by JackieXuu** [comment]
> Yes, probably due to the lit-llama update, you need to use adapter or lora to finetune LLaMA. I have tested the code again with old lit-llama version on my server and got the following result：
> 
> ```
> 
> ### Response:
> ===================
> token shape: torch.Size([211])
> Step 1. Open the fridge
> Step 2. Grasp a loaf of bread
> Step 3. Place the bread on the countertop
> Step 4. Use a butterknife to spread butter on the bread
> Step 5. Grasp lettuce, tomato, and potato
> Step 6. Place the lettuce, tomato, and potato on the bread
> Step 7. Grasp a knife and place it on the bread
> Step 8. Use the knife to cut the vegetables into slices
> Step 9. Place the sliced vegetables on top of the bread
> Step 10. Grasp a plate
> Step 11. Place the sandwich on the plate
> Step 12. Move to the person and hand it over
> Step 13. Done
> 
> 
> Time for inference: 24.09 sec total, 7.51 tokens/sec
> Memory used: 7.83 GB
> ```

Yeah, I will try again. Thanks!
